<?php
/**
 * @file
 *
 * Custom functionality for benjaminrasmussen.net
 */

/**
* Implements hook_entity_info_alter().
*/
function br_site_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['frontpage_breaking'] = array(
    'label' => t('Frontpage Breaking'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['frontpage_hot'] = array(
    'label' => t('Frontpage Hot'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['frontpage_default'] = array(
    'label' => t('Frontpage Default'),
    'custom settings' => TRUE,
  );
}